### ISSUE TITLE
Project does not compile with Java8

### ISSUE THREAD

**Issue by confile** [nmorel/gwt-jackson#41] opened 2015-01-14 11:51 UTC
I tried to compile a project using gwt-jackson 0.7 with GWT2.8SNAPSHOT and Java8. I got the following errors: 

```
Compiling module com.test.Test
   Tracing compile failure path for type 'com.github.nmorel.gwtjackson.client.JsonSerializationContext'
      [ERROR] Errors in 'com/github/nmorel/gwtjackson/client/JsonSerializationContext.java'
         [ERROR] Line 480: ObjectIdGenerator cannot be resolved to a type
         [ERROR] Line 470: ObjectIdGenerator cannot be resolved to a type
         [ERROR] Line 479: ObjectIdGenerator cannot be resolved to a type
         [ERROR] Line 468: ObjectIdGenerator cannot be resolved to a type
         [ERROR] Line 483: ObjectIdGenerator cannot be resolved to a type
         [ERROR] Line 253: ObjectIdGenerator cannot be resolved to a type
         [ERROR] Line 466: ObjectIdGenerator cannot be resolved to a type
         [ERROR] Line 467: ObjectIdGenerator cannot be resolved to a type
         [ERROR] Line 27: The import com.fasterxml.jackson.annotation.ObjectIdGenerator cannot be resolved
         [ERROR] Line 481: ObjectIdGenerator cannot be resolved to a type
   Tracing compile failure path for type 'com.github.nmorel.gwtjackson.client.deser.bean.TypeDeserializationInfo'
      [ERROR] Errors in 'com/github/nmorel/gwtjackson/client/deser/bean/TypeDeserializationInfo.java'
         [ERROR] Line 34: As cannot be resolved to a type
         [ERROR] Line 22: The import com.fasterxml.jackson.annotation.JsonTypeInfo cannot be resolved
         [ERROR] Line 44: As cannot be resolved to a type
         [ERROR] Line 55: As cannot be resolved to a type
         [ERROR] Line 43: As cannot be resolved to a type
         [ERROR] Line 54: As cannot be resolved to a type
   Tracing compile failure path for type 'com.github.nmorel.gwtjackson.client.ser.bean.TypeSerializationInfo'
      [ERROR] Errors in 'com/github/nmorel/gwtjackson/client/ser/bean/TypeSerializationInfo.java'
         [ERROR] Line 34: As cannot be resolved to a type
         [ERROR] Line 22: The import com.fasterxml.jackson.annotation.JsonTypeInfo cannot be resolved
         [ERROR] Line 44: As cannot be resolved to a type
         [ERROR] Line 55: As cannot be resolved to a type
         [ERROR] Line 43: As cannot be resolved to a type
         [ERROR] Line 54: As cannot be resolved to a type
   Tracing compile failure path for type 'com.github.nmorel.gwtjackson.client.deser.bean.AbstractIdentityDeserializationInfo'
      [ERROR] Errors in 'com/github/nmorel/gwtjackson/client/deser/bean/AbstractIdentityDeserializationInfo.java'
         [ERROR] Line 4: The import com.fasterxml.jackson.annotation.ObjectIdGenerator cannot be resolved
         [ERROR] Line 48: IdKey cannot be resolved to a type
         [ERROR] Line 47: IdKey cannot be resolved to a type
   Tracing compile failure path for type 'com.gwtplatform.dispatch.rest.client.DefaultRestRequestBuilderFactory'
      [ERROR] Errors in 'com/gwtplatform/dispatch/rest/client/DefaultRestRequestBuilderFactory.java'
         [ERROR] Line 144: MediaType cannot be resolved to a variable
         [ERROR] Line 26: The import javax.ws cannot be resolved
         [ERROR] Line 145: HttpHeaders cannot be resolved to a variable
         [ERROR] Line 27: The import javax.ws cannot be resolved
         [ERROR] Line 144: HttpHeaders cannot be resolved to a variable
   Tracing compile failure path for type 'com.github.nmorel.gwtjackson.client.ser.bean.AbstractBeanJsonSerializer'
      [ERROR] Errors in 'com/github/nmorel/gwtjackson/client/ser/bean/AbstractBeanJsonSerializer.java'
         [ERROR] Line 144: PROPERTY cannot be resolved to a variable
         [ERROR] Line 188: The method getInclude() from the type TypeSerializationInfo refers to the missing type As
         [ERROR] Line 172: WRAPPER_ARRAY cannot be resolved to a variable
         [ERROR] Line 157: WRAPPER_OBJECT cannot be resolved to a variable
         [ERROR] Line 143: The method getInclude() from the type TypeSerializationInfo refers to the missing type As
      [ERROR] Errors in 'com/github/nmorel/gwtjackson/client/ser/bean/SubtypeSerializer.java'
         [ERROR] Line 68: The method getInclude() from the type TypeSerializationInfo refers to the missing type As
         [ERROR] Line 69: WRAPPER_OBJECT cannot be resolved to a variable
      [ERROR] Errors in 'com/github/nmorel/gwtjackson/client/ser/bean/TypeSerializationInfo.java'
         [ERROR] Line 34: As cannot be resolved to a type
         [ERROR] Line 22: The import com.fasterxml.jackson.annotation.JsonTypeInfo cannot be resolved
         [ERROR] Line 44: As cannot be resolved to a type
         [ERROR] Line 55: As cannot be resolved to a type
         [ERROR] Line 43: As cannot be resolved to a type
         [ERROR] Line 54: As cannot be resolved to a type
      [ERROR] Errors in 'com/github/nmorel/gwtjackson/client/JsonSerializationContext.java'
         [ERROR] Line 480: ObjectIdGenerator cannot be resolved to a type
         [ERROR] Line 470: ObjectIdGenerator cannot be resolved to a type
         [ERROR] Line 479: ObjectIdGenerator cannot be resolved to a type
         [ERROR] Line 468: ObjectIdGenerator cannot be resolved to a type
         [ERROR] Line 483: ObjectIdGenerator cannot be resolved to a type
         [ERROR] Line 253: ObjectIdGenerator cannot be resolved to a type
         [ERROR] Line 466: ObjectIdGenerator cannot be resolved to a type
         [ERROR] Line 467: ObjectIdGenerator cannot be resolved to a type
         [ERROR] Line 27: The import com.fasterxml.jackson.annotation.ObjectIdGenerator cannot be resolved
         [ERROR] Line 481: ObjectIdGenerator cannot be resolved to a type
      [ERROR] Errors in 'com/github/nmorel/gwtjackson/client/JsonSerializerParameters.java'
         [ERROR] Line 24: The import com.fasterxml.jackson.annotation.JsonInclude cannot be resolved
         [ERROR] Line 140: Include cannot be resolved to a type
         [ERROR] Line 136: Include cannot be resolved to a type
         [ERROR] Line 76: Include cannot be resolved to a type
         [ERROR] Line 76: Include cannot be resolved to a variable
         [ERROR] Line 137: Include cannot be resolved to a type
         [ERROR] Line 141: Include cannot be resolved to a type
   Tracing compile failure path for type 'com.github.nmorel.gwtjackson.client.deser.bean.PropertyIdentityDeserializationInfo'
      [ERROR] Errors in 'com/github/nmorel/gwtjackson/client/deser/bean/PropertyIdentityDeserializationInfo.java'
         [ERROR] Line 4: The import com.fasterxml.jackson.annotation.ObjectIdGenerator cannot be resolved
         [ERROR] Line 45: IdKey cannot be resolved to a type
         [ERROR] Line 46: IdKey cannot be resolved to a type
   Tracing compile failure path for type 'com.github.nmorel.gwtjackson.client.ser.bean.SubtypeSerializer'
      [ERROR] Errors in 'com/github/nmorel/gwtjackson/client/ser/bean/SubtypeSerializer.java'
         [ERROR] Line 68: The method getInclude() from the type TypeSerializationInfo refers to the missing type As
         [ERROR] Line 69: WRAPPER_OBJECT cannot be resolved to a variable
      [ERROR] Errors in 'com/github/nmorel/gwtjackson/client/ser/bean/TypeSerializationInfo.java'
         [ERROR] Line 34: As cannot be resolved to a type
         [ERROR] Line 22: The import com.fasterxml.jackson.annotation.JsonTypeInfo cannot be resolved
         [ERROR] Line 44: As cannot be resolved to a type
         [ERROR] Line 55: As cannot be resolved to a type
         [ERROR] Line 43: As cannot be resolved to a type
         [ERROR] Line 54: As cannot be resolved to a type
      [ERROR] Errors in 'com/github/nmorel/gwtjackson/client/ser/bean/AbstractBeanJsonSerializer.java'
         [ERROR] Line 144: PROPERTY cannot be resolved to a variable
         [ERROR] Line 188: The method getInclude() from the type TypeSerializationInfo refers to the missing type As
         [ERROR] Line 172: WRAPPER_ARRAY cannot be resolved to a variable
         [ERROR] Line 157: WRAPPER_OBJECT cannot be resolved to a variable
         [ERROR] Line 143: The method getInclude() from the type TypeSerializationInfo refers to the missing type As
      [ERROR] Errors in 'com/github/nmorel/gwtjackson/client/JsonSerializationContext.java'
         [ERROR] Line 480: ObjectIdGenerator cannot be resolved to a type
         [ERROR] Line 470: ObjectIdGenerator cannot be resolved to a type
         [ERROR] Line 479: ObjectIdGenerator cannot be resolved to a type
         [ERROR] Line 468: ObjectIdGenerator cannot be resolved to a type
         [ERROR] Line 483: ObjectIdGenerator cannot be resolved to a type
         [ERROR] Line 253: ObjectIdGenerator cannot be resolved to a type
         [ERROR] Line 466: ObjectIdGenerator cannot be resolved to a type
         [ERROR] Line 467: ObjectIdGenerator cannot be resolved to a type
         [ERROR] Line 27: The import com.fasterxml.jackson.annotation.ObjectIdGenerator cannot be resolved
         [ERROR] Line 481: ObjectIdGenerator cannot be resolved to a type
      [ERROR] Errors in 'com/github/nmorel/gwtjackson/client/JsonSerializerParameters.java'
         [ERROR] Line 24: The import com.fasterxml.jackson.annotation.JsonInclude cannot be resolved
         [ERROR] Line 140: Include cannot be resolved to a type
         [ERROR] Line 136: Include cannot be resolved to a type
         [ERROR] Line 76: Include cannot be resolved to a type
         [ERROR] Line 76: Include cannot be resolved to a variable
         [ERROR] Line 137: Include cannot be resolved to a type
         [ERROR] Line 141: Include cannot be resolved to a type
   Tracing compile failure path for type 'com.fasterxml.jackson.annotation.JsonAutoDetect'
      [ERROR] Errors in 'com/github/nmorel/gwtjackson/super/com/fasterxml/jackson/annotation/JsonAutoDetect.java'
         [ERROR] Line 13: JacksonAnnotation cannot be resolved to a type
   Tracing compile failure path for type 'com.github.nmorel.gwtjackson.client.deser.bean.AbstractBeanJsonDeserializer'
      [ERROR] Errors in 'com/github/nmorel/gwtjackson/client/deser/bean/AbstractBeanJsonDeserializer.java'
         [ERROR] Line 225: The method getInclude() from the type TypeDeserializationInfo refers to the missing type As
         [ERROR] Line 370: The method newIdKey(Object) from the type IdentityDeserializationInfo refers to the missing type IdKey
         [ERROR] Line 28: The import com.fasterxml.jackson.annotation.JsonTypeInfo cannot be resolved
         [ERROR] Line 214: WRAPPER_ARRAY cannot be resolved to a variable
         [ERROR] Line 177: PROPERTY cannot be resolved to a variable
         [ERROR] Line 173: The method getInclude() from the type TypeDeserializationInfo refers to the missing type As
         [ERROR] Line 204: WRAPPER_OBJECT cannot be resolved to a variable
         [ERROR] Line 171: As cannot be resolved to a variable
         [ERROR] Line 157: The method newIdKey(Object) from the type IdentityDeserializationInfo refers to the missing type IdKey
         [ERROR] Line 168: As cannot be resolved to a type
   Tracing compile failure path for type 'com.github.nmorel.gwtjackson.client.JsonSerializerParameters'
      [ERROR] Errors in 'com/github/nmorel/gwtjackson/client/JsonSerializerParameters.java'
         [ERROR] Line 24: The import com.fasterxml.jackson.annotation.JsonInclude cannot be resolved
         [ERROR] Line 140: Include cannot be resolved to a type
         [ERROR] Line 136: Include cannot be resolved to a type
         [ERROR] Line 76: Include cannot be resolved to a type
         [ERROR] Line 76: Include cannot be resolved to a variable
         [ERROR] Line 137: Include cannot be resolved to a type
         [ERROR] Line 141: Include cannot be resolved to a type
   Tracing compile failure path for type 'com.github.nmorel.gwtjackson.client.JsonDeserializationContext'
      [ERROR] Errors in 'com/github/nmorel/gwtjackson/client/JsonDeserializationContext.java'
         [ERROR] Line 243: IdKey cannot be resolved to a type
         [ERROR] Line 250: IdKey cannot be resolved to a type
         [ERROR] Line 245: IdKey cannot be resolved to a type
         [ERROR] Line 252: IdKey cannot be resolved to a type
         [ERROR] Line 24: The import com.fasterxml.jackson.annotation.ObjectIdGenerator cannot be resolved
         [ERROR] Line 125: IdKey cannot be resolved to a type
         [ERROR] Line 251: IdKey cannot be resolved to a type
         [ERROR] Line 244: IdKey cannot be resolved to a type
         [ERROR] Line 247: IdKey cannot be resolved to a type
   Tracing compile failure path for type 'com.fasterxml.jackson.annotation.JsonFormat'
      [ERROR] Errors in 'com/github/nmorel/gwtjackson/super/com/fasterxml/jackson/annotation/JsonFormat.java'
         [ERROR] Line 14: JacksonAnnotation cannot be resolved to a type
   Tracing compile failure path for type 'com.github.nmorel.gwtjackson.client.deser.bean.IdentityDeserializationInfo'
      [ERROR] Errors in 'com/github/nmorel/gwtjackson/client/deser/bean/IdentityDeserializationInfo.java'
         [ERROR] Line 45: IdKey cannot be resolved to a type
         [ERROR] Line 19: The import com.fasterxml.jackson.annotation.ObjectIdGenerator cannot be resolved
   Tracing compile failure path for type 'com.github.nmorel.gwtjackson.client.annotation.JsonMixIns'
      [ERROR] Errors in 'com/github/nmorel/gwtjackson/client/annotation/JsonMixIns.java'
         [ERROR] Line 24: The import com.fasterxml.jackson.annotation.JacksonAnnotation cannot be resolved
         [ERROR] Line 42: JacksonAnnotation cannot be resolved to a type
   [ERROR] Aborting compile due to errors in some input files
```

**Comment by nmorel** [comment] 2015-01-14 12:17
It's odd. It's like the compiler doesn't see external source files. 
It only fails in type contained in jackson-annotations or jax-rs api.

**Comment by nmorel** [comment] 2015-01-14 12:18
GWTP is also impacted : 
```
Tracing compile failure path for type 'com.gwtplatform.dispatch.rest.client.DefaultRestRequestBuilderFactory'
      [ERROR] Errors in 'com/gwtplatform/dispatch/rest/client/DefaultRestRequestBuilderFactory.java'
         [ERROR] Line 144: MediaType cannot be resolved to a variable
         [ERROR] Line 26: The import javax.ws cannot be resolved
         [ERROR] Line 145: HttpHeaders cannot be resolved to a variable
         [ERROR] Line 27: The import javax.ws cannot be resolved
         [ERROR] Line 144: HttpHeaders cannot be resolved to a variable
```

**Comment by confile** [comment] 2015-01-14 12:24
Yes I use GWTP as well.

**Comment by nmorel** [comment] 2015-01-14 20:12
I just compiled my gwtp example with java 1.8, GWT 2.8.0-SNAPSHOT, GWTP 1.4-SNAPSHOT and gwt-jackson-0.7.1-SNAPSHOT without errors.

**Comment by nmorel** [comment] 2015-01-14 20:30
I only see the same kind of error in the guava extension. But I see that this is a known issue with guava.

**Comment by confile** [comment] 2015-01-14 20:31
Could you please link the issue?

**Comment by nmorel** [comment] 2015-01-14 20:32
https://code.google.com/p/google-web-toolkit/issues/detail?id=9036

**Comment by nmorel** [comment] 2015-01-14 20:34
Not sure it's the same problem though. But there is not much I can do I think.

**Comment by confile** [comment] 2015-01-14 20:34
You can at least rate the issue.

**Comment by bauna** [comment] 2015-08-14 19:56
I have made some changes to make it compile with java8 but not ready to be merged:
https://github.com/bauna/gwt-jackson/tree/gwt280

**Comment by nmorel** [comment] 2015-10-24 10:37
I made a few tweaks around cast. With last snapshot of gwt and guava, I have no issues on compilation and tests.

**Comment by bauna** [comment] 2015-11-26 18:03
It works except for one guava class: TreeMultisetJsonDeserializer (I think that the issue is because it requires that the generic T must be Comparable)
```
[INFO]    Adding '100' new generated units
[INFO]       See snapshot: /tmp/gwtjackson.java.lang.ObjectBeanJsonDeserializerImpl7502692652060705091.java
[INFO]       Ignored 1 unit with compilation errors in first pass.
[INFO] Compile with -strict or with -logLevel set to TRACE or DEBUG to see all errors.
[INFO]    [ERROR] Errors in '/home/bauna/dev/skymira/eforms/eforms-ui/target/.generated/gwtjackson/java/lang/ObjectBeanJsonDeserializerImpl.java'
[INFO]       [ERROR] Line 140: The method newInstance(JsonDeserializer<T>) in the type TreeMultisetJsonDeserializer is not applicable for the arguments (ObjectBeanJsonDeserializerImpl)
[INFO]       See snapshot: /tmp/gwtjackson.java.lang.ObjectBeanJsonDeserializerImpl2465895653503980292.java
[INFO]    Tracing compile failure path for type 'gwtjackson.java.lang.ObjectBeanJsonDeserializerImpl'
[INFO]       [ERROR] Errors in '/home/bauna/dev/skymira/eforms/eforms-ui/target/.generated/gwtjackson/java/lang/ObjectBeanJsonDeserializerImpl.java'
[INFO]          [ERROR] Line 140: The method newInstance(JsonDeserializer<T>) in the type TreeMultisetJsonDeserializer is not applicable for the arguments (ObjectBeanJsonDeserializerImpl)
[INFO]    [ERROR] Hint: Check that the type name 'gwtjackson.java.lang.ObjectBeanJsonDeserializerImpl' is really what you meant
[INFO]    [ERROR] Hint: Check that your classpath includes all required source roots
[INFO] 2015-11-26 14:35:28,085 user:na INFO  org.hibernate.validator.util.Version - Hibernate Validator 4.1.0.Final
[INFO] 2015-11-26 14:35:28,091 user:na INFO  org.hibernate.validator.engine.resolver.DefaultTraversableResolver - Instantiated an instance of org.hibernate.validator.engine.resolver.JPATraversableResolver.
```

**Comment by nmorel** [comment] 2015-12-04 09:55
The deserializers no longer require Comparable.

**Comment by nmorel** [comment] 2016-08-07 16:44
Seems to be working now

**Closed by nmorel** 2016-08-07 16:44 UTC
Labels: bug
